services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3011:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - GOOGLE_SHEETS_WEBHOOK_URL=${GOOGLE_SHEETS_WEBHOOK_URL}
    restart: always
